apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  selector:
    matchLabels:
      app: expiration
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: expiration
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: expiration
          image: rajasingh545/expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: data-store
                  key: nats-uri
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: data-store
                  key: nats-cluster-id
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: data-store
                  key: expiration-redis-host
